### PR TITLE
Reuse connection params from resource model in executor

### PR DESCRIPTION
**Pull request by aliksend**
Store kubernetes settings in node params and then read it in common.py
#55

### CODE REVIEW

**Review by ltamaster — CHANGES_REQUESTED** [review]

**Comment by kdebisschop** [comment]
This basic approach is working for me -- it would be lovely to reduce this patch down to the changes in pods-resource-model.py and common.py that are the functional changes and get that integrated. It's a critical feature IMO, I cannot live with the idea of repeating the same auth info in literally hundreds of node steps that run our current infrastructure.

**Comment by kdebisschop** [comment]
@ltamaster would you accept an alternate pull request that did not have file conflicts and did not remove the script args?

**Comment by ltamaster** [comment]
@kdebisschop that is ok for me

**Comment by kdebisschop** [comment]
@ltamaster Excellent!

See #99

**Pull request closed without merging**
